name: 'NexiusAI Deploy Action'
description: 'NexiusAI Deploy to Azure Container App'
inputs:
  AZURE_COMMAND_LOGIN:
    description: 'Azure login command'
    required: true
    default: ''
  AZURE_INSTANCE_NAME:
    description: 'Azure instance name'
    required: true
    default: ''
  AZURE_RESOURCE_GROUP_NAME:
    description: 'Azure resource group name'
    required: true
    default: ''
  DOCKER_IMAGE_NAME:
    description: 'Docker image name'
    required: true
    default: ''
  DOCKER_IMAGE_TAG:
    description: 'Docker image tag'
    required: true
    default: ''
  DOCKER_REGISTRY_HOSTNAME:
    description: 'Docker registry hostname'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Run az command in docker
      shell: bash
      run: |
        IMAGE_TAG="${{ inputs.DOCKER_IMAGE_TAG }}"
        IMAGE_TAG_CLEANED=$(echo "$IMAGE_TAG" | sed 's|/|_|g')
        IMAGE_NAME_CLEANED="${{ inputs.DOCKER_IMAGE_NAME }}":$IMAGE_TAG_CLEANED
        IMAGE_FULL_NAME="${{ inputs.DOCKER_REGISTRY_HOSTNAME }}/$IMAGE_NAME_CLEANED"
        echo $IMAGE_FULL_NAME
        docker run mcr.microsoft.com/azure-cli bash -c "${{inputs.AZURE_COMMAND_LOGIN}} && az containerapp update -n ${{ inputs.AZURE_INSTANCE_NAME }} -g ${{ inputs.AZURE_RESOURCE_GROUP_NAME }} --image $IMAGE_FULL_NAME  --set-env-vars VERSION=${{github.run_number}}"
