name: 'NexiusAI Deploy Action'
description: 'NexiusAI Deploy to Azure Container App'
inputs:
  AZURE_CLIENT_ID:
    description: 'Azure client ID'
    required: true
  AZURE_CLIENT_SECRET:
    description: 'Azure client secret'
    required: true
  AZURE_TENANT_ID:
    description: 'Azure tenant ID'
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: 'Azure subscription ID'
    required: true
  AZURE_REGISTRY_NAME:
    description: 'Azure registry name'
    required: true
  AZURE_INSTANCE_NAME:
    description: 'Azure instance name'
    required: true
  AZURE_RESOURCE_GROUP_NAME:
    description: 'Azure resource group name'
    required: true
  IMAGE_NAME:
    description: 'Docker image name'
    required: true
  IMAGE_TAG:
    description: 'Docker image tag'
    required: true
  IMAGE_POSTFIX:
    description: 'Image Postfix'
    required: false
    default: ''
  INSTALL_AZ_CLI:
    description: 'Install Azure CLI'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      if: ${{inputs.INSTALL_AZ_CLI == 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login to Azure
      shell: bash
      run: az login --service-principal -u ${{ inputs.AZURE_CLIENT_ID }} -p ${{ inputs.AZURE_CLIENT_SECRET }} --tenant ${{ inputs.AZURE_TENANT_ID }} && az account set --subscription ${{ inputs.AZURE_SUBSCRIPTION_ID }}
    - name: Update Azure Container App
      shell: bash
      run: |
        IMAGE_TAG="${{ inputs.IMAGE_TAG }}_${{ inputs.IMAGE_POSTFIX }}"
        IMAGE_TAG_CLEANED=$(echo "$IMAGE_TAG" | sed 's|/|_|g')
        IMAGE_NAME_CLEANED="${{ inputs.IMAGE_NAME }}":$IMAGE_TAG_CLEANED
        IMAGE_FULL_NAME="${{ inputs.AZURE_REGISTRY_NAME }}/$IMAGE_NAME_CLEANED"
        az containerapp update -n ${{ inputs.AZURE_INSTANCE_NAME }} -g ${{ inputs.AZURE_RESOURCE_GROUP_NAME }} --image $IMAGE_FULL_NAME  --set-env-vars VERSION_NUMBER_PATCH=${{github.run_number}}
