name: Build and Deploy
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build Docker Image And Extract Files For Testing
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} && az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build Docker Image
        run: az acr login --name crzsolt
      - name: get
        run: docker pull nginx:alpine
      - name: beta
        run: docker tag nginx:alpine crzsolt.azurecr.io/nginx:{{ github.run_number }}
      - name: gamma
        run: docker push crzsolt.azurecr.io/nginx:{{ github.run_number }}