name: Build and Deploy
on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  id-token: write
  contents: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  build:
    name: Build Docker Image And Extract Files For Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        uses: nexius-learning/nexiusai-action/build@v3
        with:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_REGISTRY_NAME: ${{ vars.AZURE_REGISTRY_NAME }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.ref_name }}
          IMAGE_POSTFIX: ${{ github.run_number}}
